-  hosts: all
   tasks:
   - name: Install lamp stack
     apt:
       pkg:
       - apache2   
       - mysql-server
       - php7.0
       - php7.0-mysql   
       state: present
       update cache: yes
   - name: start apache server
     service: 
       name: apache2
       state: started
       enabled: yes
   - name: start mysql service
     services:
       name: mysql
       state: started
       enabled: yes
   - name:  create target directory
     file: path=/var/www/html state=directory mode=0755
   - name:  deploy index.html
     copy: 
       src: /etc/ansible/index/index.html
       dest: var/www/html/index/index.html
