---
- hosts: group2
  vars:
    nexus_version: 3  
    nexus_download_url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    nexus_download_dest: /tmp/nexus-{{3}}-bundle.tar.gz
    nexus_extracted_dir: /tmp/nexus_extracted_dir
    nexus_dir: /usr/local/nexus
  tasks:
  - name: install java
    yum: name=java state=present
  - name: create "nexus" group
    group: name=nexus 
  - name: create "nexus" user
    user: name=nexus group=nexus 
  - name: download nexus
    get_url: url={{nexus_download_url}} dest={{nexus_download_dest}}
  - name: extract nexus to {{nexus_dir}}
    command: tar xzf {{nexus_download_dest}} -C {{nexus_dir}} --strip-components=1
    when: nexus_download.changed
  - name: make {{nexus_dir}} directory property of "nexus" user/group
    file: path={{nexus_dir}} group=nexus owner=nexus recurse=true
  - name: make nexus runned by "nexus" user
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="#RUN_AS_USER=" line="RUN_AS_USER=nexus" backrefs=true
  - name: set NEXUS_HOME
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^NEXUS_HOME" line="NEXUS_HOME={{nexus_dir}}" backrefs=true
  - name: create nexus piddir
    file: path=/var/run/nexus state=directory group=nexus owner=nexus
  - name: set nexus pidir
    lineinfile: dest={{nexus_dir}}/bin/nexus regexp="^#PIDDIR=" line="PIDDIR=/var/run/nexus" backrefs=true
  - name: create symbolic links to /etc/init.d/nexus
    file: src={{nexus_dir}}/bin/nexus dest=/etc/init.d/nexus state=link
  - name: configure runlevel links for nexus
    command: update-rc.d nexus defaults
  - name: set nexus working directory
    lineinfile: dest={{nexus_dir}}/conf/nexus.properties regexp="^nexus-work=" line="nexus-work=${bundleBasedir}/work/nexus"
  - name: start nexus
    service: name=nexus state=started pattern={{nexus_dir}}
    
